"""Configuration and constants for the Seek scraper."""

# Search configuration
CLASSIFICATION = "information-communication-technology"
LOCATION = "All-Melbourne-VIC"
BASE_URL = "https://www.seek.com.au"

# Scraping settings
DEFAULT_WORKERS = 20
MAX_WORKERS = 20
CHECKPOINT_INTERVAL = 50
MAX_PAGES = 100

# Timeout settings (in seconds)
PAGE_LOAD_TIMEOUT = 1.5
ELEMENT_WAIT_TIMEOUT = 1.5
BRIEF_PAUSE = 0.2
PAGE_TRANSITION = 0.8
PAGINATION_SCROLL = 0.8

# Chrome options
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Google enrichment settings
ENABLE_GOOGLE_ENRICHMENT = True
GOOGLE_SEARCH_DELAY = 3

# Data columns
COLUMNS = [
    'job_title', 'company', 'location', 'classification', 
    'work_type', 'salary', 'time_posted', 
    'email', 'phone', 'office_phone', 'website', 'url'
]

# Invalid website domains to filter
INVALID_DOMAINS = [
    'ogp.me', 'schema.org', 'w3.org', 'xmlns.com', 'example.com',
    'facebook.com/sharer', 'twitter.com/intent', 'linkedin.com/sharing'
]

# Recruitment companies to filter out (case-insensitive matching)
RECRUITMENT_COMPANIES = [
    'Recruitment',
    'Recruiters',
    'Recruiting',
    'Staffing',
    'Staffing Solutions',
    'Talent Solutions',
    'Recruit',
    'Consulting',
    'Hays Technology',
    'Hays',
    'Robert Half Technology',
    'Robert Half',
    'Michael Page Technology',
    'Michael Page',
    'Paxus',
    'Talent',
    'Peoplebank',
    'Finite IT',
    'Greythorn',
    'Halcyon Knights',
    'Lanson Partners',
    'Ignite',
    'Morgan McKinley Technology',
    'Morgan McKinley',
    'Clicks IT Recruitment',
    'Clicks IT',
    'Ambition Technology',
    'Ambition',
    'Davidson Technology',
    'Davidson',
    'Charterhouse IT',
    'Charterhouse',
    'Sirius Technology',
    'Sirius',
    'Bluefin Resources',
    'Bluefin',
    'Hudson Australia',
    'Hudson',
    'Expert360',
    'Launch Recruitment',
    'CircuIT Recruitment',
    'CircuIT',
    'Randstad Digital',
    'Randstad',
    'Emmbr',
    'Pathfinder Recruitment',
    'SALT SEARCH PTY LTD',
    'Talenza',
    'Slade Group',
    'Experis AU',
    'Precision Sourcing',
    'Opus Recruitment Solutions',
    'Reo Group',
    'Robert Walters',
    'Woods & Co',
    'Natural Selection Group',
    'Evolution Recruitment Solutions Pty Ltd',
    'Recruitment Professionals Pty Ltd',
    'GradConnection',
    'The Decipher Bureau',
    'Green Light PS Pty Ltd',
    'Morgan Consulting',
    'Nigel Frank International',
    'Genesis IT Recruitment',
    'FourQuarters Recruitment',
    'Just Digital People',
    'BSS INSIGHT PTY LTD',
    'Refactor Recruitment Pty Ltd',
    'Shield Recruitment',
    'SustainRecruit',
    'FinXL IT Professional Services',
    'Conquest Recruitment Group Pty Ltd',
    'Recruitment Hive',
    'Scalene Group Pty Ltd',
    'Mars Recruitment',
    'Dynamo Recruitment',
    'The Onset',
    'Aurec',
]

# Victorian Government Departments and Agencies
GOV_COMPANIES = [
    # Departments
    "Education and Training",
    "Environment, Land, Water and Planning",
    "Families, Fairness and Housing",
    "Health",
    "Jobs, Precincts and Regions",
    "Justice and Community Safety",
    "Premier and Cabinet",
    "Transport",
    "Treasury and Finance",
    # Key Agencies
    "Cenitex",
    "Commercial Passenger Vehicle Commission",
    "Essential Services Commission",
    "Environment Protection Authority",
    "Game Management Authority",
    "Independent Broad-Based Anti-Corruption Commission",
    "Infrastructure Victoria",
    "Office of Public Prosecutions and Associate Crown Prosecutors",
    "Office of the Chief Commissioner of Police (Victoria Police)",
    "Office of the Commissioner for Environmental Sustainability",
    "Office of the Commission for Children and Young People",
    "Office of the Labour Hire Licensing Authority",
    "Office of the Legal Services Commissioner",
    "Office of the Ombudsman",
    "Office of the Road Safety Camera Commissioner",
    "Office of the Victorian Disability Worker Commissioner",
    "Office of the Victorian Information Commissioner",
    "Portable Long Service Benefits Authority",
    "Victorian Auditor-General's Office",
    "Victorian Commission for Gambling and Liquor Regulation",
    "Victorian Electoral Commission",
    "Victorian Equal Opportunity and Human Rights",
    "Victorian Fisheries Authority",
    "Victorian Inspectorate",
    "Victorian Public Sector Commission",
    "Victorian Responsible Gambling Foundation",
    # Education & Training
    "Adult Community and Further Education Board",
    "Adult Multicultural Education Services (AMES Aust)",
    "Bendigo TAFE",
    "Box Hill Institute of TAFE",
    "Chisholm Institute",
    "Federation Training - TAFE Gippsland",
    "Gordon Institute of TAFE",
    "Goulburn Ovens Institute of TAFE",
    "Holmesglen Institute of TAFE",
    "Melbourne Polytechnic",
    "South West Institute of TAFE",
    "Sunraysia Institute of TAFE",
    "Victorian Curriculum and Assessment Authority (VCAA)",
    "Victorian Institute of Teaching",
    "Victorian Registration and Qualifications Authority",
    "William Angliss Institute of TAFE",
    "Wodonga Institute of TAFE",
    # Environment, Water & Planning
    "Alpine Resorts Co-ordinating Council",
    "Architects' Registration Board of Victoria",
    "Barwon Region Water Corporation",
    "Central Gippsland Region Water Corporation",
    "Central Highlands Region Water Corporation",
    "City West Water Corporation",
    "Cladding Safety Victoria",
    "Coliban Region Water Corporation",
    "Corangamite Catchment Management Authority",
    "Dhelkunya Dja Land Management Board",
    "East Gippsland Catchment Management Authority",
    "East Gippsland Region Water Corporation",
    "Energy Safe Victoria",
    "Falls Creek Alpine Resort Management Board",
    "Glenelg Hopkins Catchment Management Authority",
    "Goulburn Broken Catchment Management Authority",
    "Goulburn Valley Region Water Corporation",
    "Goulburn Valley Waste and Resource Recovery Group",
    "Goulburn-Murray Rural Water Corporation",
    "Grampians Central Waste and Resource Recovery Group",
    "GWM Water (Grampians Wimmera-Mallee Water Corporation)",
    "Lower Murray Urban and Rural Water Corporation",
    "Mallee Catchment Management Authority",
    "Melbourne Water Corporation",
    "Metropolitan Waste and Resource Recovery Group",
    "Mount Buller and Mount Stirling Alpine Resort Management Board",
    "Mount Hotham Alpine Resort Management Board",
    "North Central Catchment Management Authority",
    "North East Catchment Management Authority",
    "North East Region Water Corporation",
    "Parks Victoria",
    "Phillip Island Nature Park Board of Management",
    "Port Phillip and Westernport Catchment Management Authority",
    "Royal Botanic Gardens Board of Victoria",
    "South East Water Corporation",
    "South Gippsland Water Corporation",
    "Southern Alpine Resort Management Board",
    "Southern Rural Water Corporation",
    "Surveyors Registration Board of Victoria",
    "Sustainability Victoria",
    "Trust for Nature (Victoria)",
    "Victorian Building Authority",
    "Victorian Environmental Water Holder",
    "Victorian Planning Authority",
    "Wannon Region Water Corporation",
    "West Gippsland Catchment Management Authority",
    "Western Water Corporation",
    "Westernport Region Water Corporation",
    "Wimmera Catchment Management Authority",
    "Yarra Valley Water Corporation",
    "Zoological Parks and Gardens Board",
    # Families, Fairness & Housing
    "Queen Victoria Women's Centre Trust",
    "Shrine of Remembrance",
    "Victorian Interpreting and Translating Services (VITS) Language Loop",
    # Health
    "Ambulance Victoria",
    "Ballarat General Cemeteries Trust",
    "Geelong Cemeteries Trust",
    "Greater Metropolitan Cemeteries Trust",
    "Mental Health Tribunal",
    "Remembrance Parks Central Victoria (Formerly Bendigo Cemeteries Trust)",
    "Southern Metropolitan Cemeteries Trust",
    "VicHealth (Victorian Health Promotion Foundation)",
    "Victorian Assisted Reproductive Treatment Authority",
    "Victorian Institute of Forensic Mental Health (Forensicare)",
    "Victorian Pharmacy Authority",
    # Jobs, Precincts & Regions
    "Arts Centre Melbourne",
    "Australian Centre for the Moving Image",
    "Australian Grand Prix Corporation",
    "Dairy Food Safety Victoria",
    "Emerald Tourist Railway Board",
    "Film Victoria",
    "Geelong Performing Arts Centre Trust",
    "Greyhound Racing Victoria",
    "Harness Racing Victoria",
    "Kardinia Park Stadium Trust",
    "Melbourne and Olympic Parks Trust",
    "Melbourne Convention and Exhibition Centre Trust (MCEC)",
    "Melbourne Cricket Ground Trust",
    "Melbourne Market Authority",
    "Museums Victoria",
    "National Gallery of Victoria, Council of Trustees",
    "PrimeSafe",
    "State Library of Victoria",
    "State Sports Centres Trust",
    "Veterinary Practitioners Registration Board of Victoria",
    "VicForests",
    # Justice & Community Safety
    "Accident Compensation and Conciliation Service",
    "Court Services Victoria",
    "Country Fire Authority",
    "Emergency Services Telecommunications Authority",
    "Fire Rescue Victoria",
    "Residential Tenancies Bond Authority",
    "Sentencing Advisory Council",
    "Victoria Legal Aid",
    "Victoria State Emergency Service Authority",
    "Victorian Institute of Forensic Medicine",
    "Victorian Law Reform Commission",
    "Worksafe Victoria",
    # Transport
    "Development Victoria",
    "Port of Hastings Development Authority",
    "Transport Accident Commission",
    "V/Line Corporation",
    "Victorian Ports Corporation",
    "Victorian Regional Channels Authority",
    "VicTrack",
    # Treasury & Finance
    "Emergency Services and State Superannuation Board - ESSB",
    "Treasury Corporation of Victoria",
    "Victorian Funds Management Corporation",
    "Victorian Managed Insurance Authority",
]